### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by TheChilliPL** [pawREP/ZHM5Randomizer#11]
After adding the files to `HITMAN2/Retail`, the game no longer starts and shows an error message:
![image](https://user-images.githubusercontent.com/18823939/94006583-54f29480-fda0-11ea-9288-68167191f65c.png)
If I rename the included DINPUT8.dll file, it starts working again. Doesn't work with DX11 nor 12, doesn't even show the launcher.

**Comment by TheChilliPL** [comment]
Uhh, it seems the game starts when clicking *Play* on Steam, and the mod works, but the game doesn't start when starting the executable (HITMAN2.exe) manually. If it's a known issue, worth to mention in the readme file

**Comment by pawREP** [comment]
Thanks for reminding me of this issue. It's a known issue and I added a note about it to the readme.
