### ISSUE TITLE
v 2.72.0 update in early Nov 2020

### ISSUE THREAD

**Issue by DKCTC** [pawREP/ZHM5Randomizer#12]
It looks like the timestamps in Offsets.cpp in GameOffsets::GameVersion GameOffsets::getVersion() need to be updated to be compatible with the latest update.

Unless they changed other things that will break functionality... C++ really isn't my thing, otherwise I would compile and test it myself.

I love the mod and I hope this makes it work again! Excellent job!

**Comment by warriorstar-orion** [comment]
FWIW the version number hasn't changed since the last update, which makes me assume that the change is unrelated to the engine build. I used 0x5F8D57CA as the offset for DX11 just by having it spit out what value it did find, and so far a mission runs and items are indeed randomized.

**Comment by Whaletail930** [comment]
So, I changed the offset in DX11. But now, how do I go about running the mod? How do I need to compile the source?

**Comment by Superskish** [comment]
Care to explain for dummies how to do this? I have no clue how to offset DirectX11. I don't even know if I have it lol.

**Comment by Snipa22** [comment]
Ooooh, good to know.  I'd seen that there was supposed to be some comments in the ida comment file, but I didn't see one commited or I'd go snag a copy of IDA and find the new offsets.   IIRC, there's a second release coming later this month, so it might be worth waiting until then to do any serious offset work.

**Comment by DKCTC** [comment]
As warriorstar-orion pointed out, it looks like all that might need to be changed are the timestamps. If I knew enough about how to get cmake to work, I would just update the timestamps and compile and continue on my merry way.

Can you give me any pointers on how to compile this dang thing? Thanks!

**Comment by warriorstar-orion** [comment]
Ehh, I really don't want to self-advertise, but it may be easier to use the latest build of my fork: https://github.com/warriorstar-orion/ZHM5Randomizer/releases/tag/preview6 this should have functional timestamps for DX11 and DX12. Out-of-the-box my fork should behave the same as the original. If you have issues with it, comment on my repo, not on this one.

**Comment by DKCTC** [comment]
That's awesome! Thanks for the help!

**Comment by Heartran** [comment]
So is it now compatible with the latest version of Hitman 2?

**Comment by ChoiceSquiddy** [comment]
so It's January and still not updated?
