### ISSUE TITLE
The game version is not compatible 

### ISSUE THREAD

**Issue by MSCgameplayer** [pawREP/ZHM5Randomizer#13]
i installed the mod and started the game but the current version of the mod is not compatible with the game version

**Comment by baluwastaken** [comment]
#12

**Comment by Heartran** [comment]
> i installed the mod and started the game but the current version of the mod is not compatible with the game version

Same problem

**Comment by jolaquai** [comment]
Vote to close this as it's a duplicate of #12 at @baluwastaken mentioned?
