### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by l4lm4n** [pawREP/ZHM5Randomizer#18]
I’m trying to use the randomiser mod I have downloaded the latest and have followed the guidelines but it is giving me an issue saying Vcruntline140_1.dll was not found but when I remove the randomiser mod files it plays fine ? Can you help

**Comment by pawREP** [comment]
You are missing the Microsoft Visual C++ Redistributable 2019. Installing it should fix the issue. You can download it from Microsoft's support website or use this direct link to the download: https://aka.ms/vs/16/release/vc_redist.x64.exe
