### ISSUE TITLE
Signature Scan Failed After Patch 3.30

### ISSUE THREAD

**Issue by yca321** [pawREP/ZHM5Randomizer#22]
After updating the game with the latest patch 3.30, a window popped up and says signature scan failed when the mod is installed.

**Comment by Superskish** [comment]
I'm having the same issue.

**Comment by noneedinmagic** [comment]
I looked into the source code like a week ago (because this repo seems to be abandoned), and it seems, that the mod tries to find the signatures inside .exe file which are changed to smth else. Looking for those signatures via Hex editor gets nothing, but there are a lot of different ones. Need someone who has more experience in investigating insides of Hitman exe to figure this thing out.

**Comment by noneedinmagic** [comment]
@pawREP just mentioning you as the author of this mod

I suppose that you're busy enough or just have lack of interest for this mod, but it would be nice if there was some feedback from the dev, are there any hope for any expectations here, or we are eternally doomed to remember this mod by being unable to use it? 😅

Maybe it might be possible to guide other people by explaining how did you create this mod, what it looks for in the game files, how to find new values that need to be found as signatures etc. so someone might try to fix it and submit PRs

**Comment by pawREP** [comment]
Thanks for reporting this and sorry about the long inactivity. It's less a lack of interest and more the fact that I don't actually own Hitman 3 myself, so I relied to some extent on other people for help and testing with the current version. That being said, I agree that this issue should be fixed and I'm committed to addressing it within the next few days.

**Comment by noneedinmagic** [comment]
@pawREP I tried C++ like more than 8 years ago, so right now it was somewhat difficult for me to build DLL from scratch, even needed to ask a friend for some help, but if I (and maybe anyone else who sees this comment) might help somehow, then let us know, please :)

Also, H3 is on a 25% discount in EGS for the next 3 days
