### ISSUE TITLE
Hitman Randomizer 1.43 (BRAND NEW FILE) Is not Working (For me)

### ISSUE THREAD

**Issue by sustem2020** [pawREP/ZHM5Randomizer#26]
I know it was a struggle probably to make sure the randomizer works for the 3.30 update, but for me I just downloaded the file today, and realized it ain't working again.  Again, it is for me, so idk if its for anyone else.

**Comment by Britprogamer** [comment]
New update today thats why

**Comment by sustem2020** [comment]
Ah
