### ISSUE TITLE
Randomizer Doesn't Support Game Version, again sadly : ( (For me, don't know if so for others)

### ISSUE THREAD

**Issue by sustem2020** [pawREP/ZHM5Randomizer#28]
Just got ready to play Hitman 3 with the randomizer and got the same noti like usual when it doesn't work.  Checked HITMAN YT channel and no updates, don't know if there was.  Just to clarify the incident and get it out there.

**Comment by dcortez** [comment]
same here. just tried it and it came up with the same message.

**Comment by pawREP** [comment]
The issue is being worked on. At the time of the filing of this issue, all offsets/timestamps should have been up to date, so this is a puzzling problem. For the next release I will ship some better diagnostics, that should help with debugging of this problem. ETA 0-2 days.

**Comment by sustem2020** [comment]
ok

**Comment by pawREP** [comment]
@sustem2020 The issue should be fixed in the latest release

**Comment by sustem2020** [comment]
alight
