### ISSUE TITLE
"Invalid client version"

### ISSUE THREAD

**Issue by Silent-Program** [pawREP/ZHM5Randomizer#31]
I am using the latest mod version, and it tells me it is an invalid client version.  I'm using it for hitman 2 i got the link from here https://www.reddit.com/r/HiTMAN/comments/dp9moj/hitman_2_randomizer_mod_release/

**Comment by Silent-Program** [comment]
I figured it out, you should replace the download link on the hitman 2 branch with this
https://github.com/pawREP/ZHM5Randomizer/releases/tag/v1.33

**Comment by pawREP** [comment]
Thank for reporting this. The links in the reddit post are updated now.
