### ISSUE TITLE
Needs Support for Version 3.50.0

### ISSUE THREAD

**Issue by IAmNotCoCoMelon** [pawREP/ZHM5Randomizer#35]
I sont know whats going on. But everytime I launch the game, its say unsupported client. When I remove the randomizer it launches the game. So I think the randomizer needs support for 3.50.0. If thats not the case than I have no idea whats wrong with my hitman 3.

**Comment by IAmNotCoCoMelon** [comment]
I left some spelling mistakes lol

**Comment by pawREP** [comment]
You are correct, the client that released today is not supported yet. I'll take care of it soon. I also created an issue for this already so I will close this as duplicate. ( #34 )
