### ISSUE TITLE
RNGSeed

### ISSUE THREAD

**Issue by Caleb-J773** [pawREP/ZHM5Randomizer#4]
I believe that the Randomizer is treating the RNGSeed that is set to 0 as an actual seed instead of when 0, it is supposed to randomize every time.

I've gotten the same items per restart on the same levels with just 0 as the RNGseed, however moving the number to something else then 0 resulted in a new set generated. 

0 = no seed, re-randomized at mission start.
^ does not work.

**Comment by pawREP** [comment]
Thanks for the report. The issue has been fixed with 15f0e1f
