### ISSUE TITLE
Disable certain things

### ISSUE THREAD

**Issue by Ruethy** [pawREP/ZHM5Randomizer#7]
im wondering can i disable the npc inv randomizer i keep getting 1 shotted by the striker almost the beginning of every gun fight.

also side note hitman 2 gear editor only works when randomizer is installed why is that?

**Comment by Caleb-J773** [comment]
You should be able to disable the NPC randomization, I was messing around with randomization and was able to change the configs. 
Go into the configuration `ZHM5Randomizer.ini`

For `npcInventoryRandomizer`
put in `NONE` in all upper case.
replacing `DEFAULT `with `NONE`

You could also try out the `SLEEPY` config too

This should fix that issue.


Reference File: `RandomisationMan.cpp`
![image](https://user-images.githubusercontent.com/4467576/96397484-a6bbee00-1197-11eb-8fe4-23c4d3e474da.png)

> also side note hitman 2 gear editor only works when randomizer is installed why is that?

Did you mean that the mod only works when the randomizer isn't installed?
If so it's a conflict, I hadn't used that mod, but from the sounds of it, it might be conflicting with Randomizer's inventory randomization, you can disable that part by going back into the configuration file of `ZHM5Randomizer.ini` and going to the `heroInventoryRandomizer `and replacing `DEFAULT `with `NONE`

I hadn't used that mod, so I'm not entirely sure what the conflict could be.
