### ISSUE TITLE
Where did you get the Repository.json from?

### ISSUE THREAD

**Issue by BieHDC** [pawREP/ZHM5Randomizer#8]
I know it is included in your releases, but i am curious where it came from.
Thanks. (And sorry for asking this way, but there is no other way)

**Comment by BieHDC** [comment]
Ok, i [found it](https://github.com/pawREP/ZHM5PatchBuilder/blob/master/QuickBMS_script/Hitman2_rpkg.bms) when checking your profile, but which file do i run it against?

**Comment by pawREP** [comment]
The repository file is generated from Hitman2's REPO file which you can find in `chunk0/REPO/00204d1afd76ab13.REPO` after unpacking `Runtime/chunk0.rpkg` (or the latest patch of this file) with the script you linked.
