### ISSUE TITLE
Mod does not seem to work on Hitman 2 

### ISSUE THREAD

**Issue by DaleJV** [pawREP/ZHM5Randomizer#9]
Hi there!

I did as instructed and placed the contents of the downloaded file into retail but nothing has changed in game.

I use dx12 as dx11 has a issue when trying to start the game.

**Comment by DaleJV** [comment]
Turns out the mod is what is causing dx11 to not work. Using latest version.

**Comment by Imsusbutnot** [comment]
so my game vers is 2.1.1.0 and it will not work im i doing something wrong i put the files in the right spot

**Comment by DaleJV** [comment]
I have a feeling this mod has been discontinued hence it not working for us.

**Comment by Imsusbutnot** [comment]
yah
just got hitman2 and shall this
![image](https://user-images.githubusercontent.com/73082576/96388051-02708200-116c-11eb-8395-bc60e0d23731.png)
![image](https://user-images.githubusercontent.com/73082576/96388092-39df2e80-116c-11eb-8845-2cd5ffcdf3fc.png)
if it help at all 
![image](https://user-images.githubusercontent.com/73082576/96388184-c558bf80-116c-11eb-9ecd-d9642ce9031f.png)

**Comment by Caleb-J773** [comment]
Mod works fine for me, just tried on D11
Game Version: 2.72.0.0 

Make sure you are using the release version of the mod and not the github source code. 

[https://github.com/pawREP/ZHM5Randomizer/releases](url)
